# Generated by Django 4.1.6 on 2023-08-10 10:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'directions',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('username', models.SlugField(max_length=255)),
                ('profession', models.CharField(max_length=50)),
                ('about_me', models.TextField(blank=True)),
                ('experience', models.PositiveIntegerField()),
                ('cost_30m', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(500)])),
                ('cost_1h', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)])),
                ('telegram', models.CharField(max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField()),
                ('github', models.URLField(blank=True)),
                ('behance', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('priority', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('image', models.FileField(upload_to='')),
                ('directions', models.ManyToManyField(to='mentor.direction')),
                ('topics', models.ManyToManyField(to='mentor.topic')),
            ],
            options={
                'db_table': 'mentors',
            },
        ),
    ]
