# Generated by Django 4.2.5 on 2023-10-02 08:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('about_me', ckeditor.fields.RichTextField()),
                ('experience', models.PositiveIntegerField(default=1)),
                ('cost_30m', models.PositiveIntegerField(default=0)),
                ('cost_1h', models.PositiveIntegerField(default=0)),
                ('telegram', models.CharField(max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('behance', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('priority', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('permission', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('last_update', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='mentors_images')),
                ('profession', models.ManyToManyField(to='rating.profession')),
            ],
            options={
                'db_table': 'mentors',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('profession', models.ManyToManyField(to='rating.profession')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('text', ckeditor.fields.RichTextField()),
                ('rating', models.IntegerField(default=1)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='mentor',
            name='skills',
            field=models.ManyToManyField(to='mentor.skill'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='topics',
            field=models.ManyToManyField(to='mentor.topic'),
        ),
    ]
