# Generated by Django 4.1.6 on 2023-07-28 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryExperienceOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'country_experience_offline',
            },
        ),
        migrations.CreateModel(
            name='CountryExperienceOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'country_experience_online',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'directions',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pay_methods',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mentor_skills',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mentor_tags',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('UTC', models.CharField(choices=[('UTC−12', 'UTC−12'), ('UTC−11', 'UTC−11'), ('UTC−10', 'UTC−10'), ('UTC−9', 'UTC−9'), ('UTC−8', 'UTC−8'), ('UTC−7', 'UTC−7'), ('UTC−6', 'UTC−6'), ('UTC−5', 'UTC−5'), ('UTC−4', 'UTC−4'), ('UTC−3', 'UTC−3'), ('UTC−2', 'UTC−2'), ('UTC−1', 'UTC−1'), ('UTC+0', 'UTC+0'), ('UTC+1', 'UTC+1'), ('UTC+2', 'UTC+2'), ('UTC+3', 'UTC+3'), ('UTC+4', 'UTC+4'), ('UTC+5', 'UTC+5'), ('UTC+6', 'UTC+6'), ('UTC+7', 'UTC+7'), ('UTC+8', 'UTC+8'), ('UTC+9', 'UTC+9'), ('UTC+10', 'UTC+10'), ('UTC+11', 'UTC+11'), ('UTC+12', 'UTC+12'), ('UTC+13', 'UTC+13'), ('UTC+14', 'UTC+14')], default='UTC+0', max_length=100)),
                ('profession', models.CharField(max_length=50)),
                ('years_experience', models.PositiveIntegerField()),
                ('free_15min', models.BooleanField()),
                ('cost_1week_chat', models.PositiveIntegerField()),
                ('cost_30m', models.PositiveIntegerField()),
                ('cost_1h', models.PositiveIntegerField()),
                ('cost_4h', models.PositiveIntegerField()),
                ('cost_8h', models.PositiveIntegerField()),
                ('cv_link', models.URLField(blank=True)),
                ('about_me', models.TextField()),
                ('telegram', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField()),
                ('portfolio', models.URLField(blank=True)),
                ('priority', models.BooleanField()),
                ('status', models.CharField(choices=[('public', 'Public'), ('moderation', 'Moderation'), ('disabled', 'Disabled')], default='moderation', max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('country_Experience_offline', models.ManyToManyField(to='mentor.countryexperienceoffline')),
                ('country_Experience_online', models.ManyToManyField(to='mentor.countryexperienceonline')),
                ('directions', models.ManyToManyField(to='mentor.direction')),
                ('languages', models.ManyToManyField(to='mentor.language')),
                ('pay_methods', models.ManyToManyField(to='mentor.paymethod')),
                ('skills', models.ManyToManyField(to='mentor.skill')),
                ('tags', models.ManyToManyField(blank=True, to='mentor.tag')),
                ('topics', models.ManyToManyField(to='mentor.topic')),
            ],
            options={
                'db_table': 'mentors',
            },
        ),
    ]
