# Generated by Django 4.1.6 on 2023-08-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.FileField(upload_to='mentors_images'),
        ),
    ]
