# Generated by Django 4.1.6 on 2023-09-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('directions', models.ManyToManyField(to='mentor.direction')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.AddField(
            model_name='mentor',
            name='skills',
            field=models.ManyToManyField(to='mentor.skill'),
        ),
    ]
