# Generated by Django 4.1.6 on 2023-07-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='telegram',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='whatsapp',
            field=models.CharField(max_length=50),
        ),
    ]
