# Generated by Django 4.2.5 on 2023-10-25 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
