# Generated by Django 4.1.6 on 2023-08-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_rename_cost_1week_chat_mentor_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='UTC',
            new_name='utc',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='username',
            field=models.SlugField(max_length=255),
        ),
    ]
