# Generated by Django 4.2.5 on 2023-10-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(upload_to='mentors_images'),
        ),
    ]
