# Generated by Django 4.1.6 on 2023-07-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_alter_mentor_telegram_alter_mentor_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='how_can_you_help',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='about_me',
            field=models.TextField(),
        ),
    ]
