# Generated by Django 4.2.5 on 2023-10-25 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_mentor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='cost_1h',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='cost_30m',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50000)]),
        ),
    ]
