# Generated by Django 4.1.6 on 2023-07-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_remove_mentor_how_can_you_help_alter_mentor_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='cv_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mentor.tag'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
