# Generated by Django 4.2.5 on 2023-09-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_review_created_at_review_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='username',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
