# Generated by Django 4.2.5 on 2023-09-15 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0007_alter_mentor_about_me_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
