# Generated by Django 4.1.6 on 2023-07-23 00:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prof_slug', models.SlugField(max_length=255)),
                ('status', models.CharField(choices=[('public', 'Public'), ('disabled', 'Disabled')], default='disabled', max_length=100)),
            ],
            options={
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('public', 'Public'), ('moderation', 'Moderation'), ('disabled', 'Disabled')], default='moderation', max_length=100)),
                ('grade', models.CharField(choices=[('without', 'Without'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='without', max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='VideoAnswerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('public', 'Public'), ('moderation', 'Moderation')], default='moderation', max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.question')),
            ],
            options={
                'db_table': 'video_answer_links',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(default=1)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.profession')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.profession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rating.question')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.tag'),
        ),
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('public', 'Public'), ('moderation', 'Moderation'), ('disabled', 'Disabled')], default='moderation', max_length=100)),
                ('grades', models.CharField(choices=[('without', 'Without'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='without', max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.profession')),
            ],
            options={
                'db_table': 'mock_interviews',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(default=1)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.profession')),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='ExtraContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('public', 'Public'), ('moderation', 'Moderation')], default='moderation', max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.question')),
            ],
            options={
                'db_table': 'extra_content_links',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('short_rating', models.IntegerField(default=1)),
                ('long_rating', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('public', 'Public'), ('moderation', 'Moderation')], default='moderation', max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.question')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
