# Generated by Django 4.1.6 on 2023-05-02 02:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prof_slug', models.SlugField(max_length=255)),
            ],
            options={
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tegs',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('public', 'public'), ('moderation', 'moderation'), ('disabled', 'disabled')], default='public', max_length=100)),
                ('rating_qty', models.IntegerField(default=1)),
                ('comments_qty', models.IntegerField(default=0)),
                ('links_qty', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.profession')),
                ('teg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.teg')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('rating_qty', models.IntegerField(default=1)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.question')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
