# Generated by Django 4.2.5 on 2023-10-02 08:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('public_rating', models.BooleanField()),
                ('public_mock', models.BooleanField()),
                ('public_analytic', models.BooleanField()),
                ('public_mentor', models.BooleanField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('telegram_chat', models.URLField(blank=True)),
                ('votes', models.PositiveIntegerField(blank=True)),
                ('votes_access', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], default='Не указан', max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='VideoAnswerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.question')),
            ],
            options={
                'db_table': 'video_answer_links',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('position', models.IntegerField(default=1000)),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.profession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rating.question')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.tag'),
        ),
        migrations.AddField(
            model_name='profession',
            name='tags',
            field=models.ManyToManyField(to='rating.tag'),
        ),
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('url', models.URLField()),
                ('public', models.BooleanField(default=True)),
                ('grade', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], default='Не указан', max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.profession')),
            ],
            options={
                'db_table': 'mock_interviews',
            },
        ),
        migrations.CreateModel(
            name='ExtraContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.question')),
            ],
            options={
                'db_table': 'extra_content_links',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('author', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=1)),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('url', models.URLField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.question')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
