# Generated by Django 4.1.6 on 2023-07-24 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('moderation', 'Moderation'), ('disabled', 'Disabled')], default='moderation', max_length=100),
        ),
    ]
