# Generated by Django 4.1.6 on 2023-07-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockinterview',
            name='status',
            field=models.BooleanField(),
        ),
    ]
