# Generated by Django 4.1.6 on 2023-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockinterview',
            old_name='status',
            new_name='public',
        ),
        migrations.RemoveField(
            model_name='mockinterview',
            name='grades',
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='grade',
            field=models.CharField(choices=[('не указан', 'не указан'), ('trainee', 'Trainee'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='without', max_length=100),
        ),
    ]
