# Generated by Django 4.2.5 on 2023-10-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
