# Generated by Django 4.1.6 on 2023-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='directions',
            field=models.ManyToManyField(to='rating.tag'),
        ),
    ]
