# Generated by Django 4.1.6 on 2023-07-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_question_status_rating_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='description',
            field=models.TextField(default='212', max_length=255),
        ),
    ]
