# Generated by Django 4.1.6 on 2023-07-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_mockinterview_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='profession',
        ),
        migrations.AlterField(
            model_name='profession',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.DeleteModel(
            name='KeyWord',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
