# Generated by Django 4.1.6 on 2023-08-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_profession_directions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profession',
            old_name='directions',
            new_name='tags',
        ),
    ]
