# Generated by Django 4.1.6 on 2023-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_rename_directions_profession_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='position',
            field=models.IntegerField(default=1000),
        ),
    ]
