# Generated by Django 4.2.5 on 2023-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_rating_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockinterview',
            name='grade',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], default='Не указан', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], default='Не указан', max_length=100),
        ),
    ]
