# Generated by Django 4.2.5 on 2023-09-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_alter_mockinterview_grade_alter_question_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
