# Generated by Django 4.2.5 on 2023-09-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_alter_rating_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockinterview',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='title',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='videoanswerlink',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
