# Generated by Django 4.2.5 on 2023-09-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_alter_mockinterview_public_alter_mockinterview_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='public_mentor',
        ),
    ]
