# Generated by Django 4.2.5 on 2023-09-12 02:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_remove_profession_public_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='extracontentlink',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
