# Generated by Django 4.2.5 on 2023-09-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0010_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='ip_address',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
