# Generated by Django 4.2.5 on 2023-09-14 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0012_alter_access_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
