# Generated by Django 4.2.5 on 2023-09-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0013_rating_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='data',
        ),
    ]
