# Generated by Django 4.2.5 on 2023-09-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0014_remove_rating_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
