# Generated by Django 4.2.5 on 2023-09-15 04:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0015_answer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
