# Generated by Django 4.1.6 on 2023-08-11 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('amount_vacancies', models.PositiveIntegerField()),
                ('last_update', models.DateField(default=django.utils.timezone.now)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.profession')),
            ],
            options={
                'db_table': 'searches',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=1)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytic.search')),
            ],
            options={
                'db_table': 'anaytics_skills',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=1)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytic.search')),
            ],
            options={
                'db_table': 'anaytics_keywords',
            },
        ),
    ]
