# Generated by Django 4.1.6 on 2023-08-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
