# Generated by Django 4.2.5 on 2023-09-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0002_search_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='url',
            field=models.URLField(max_length=5000),
        ),
    ]
