# Generated by Django 4.2.5 on 2023-10-02 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('delete_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accesses',
            },
        ),
    ]
